// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwipkmjonfsgrtdacggo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aXBrbWpvbmZzZ3J0ZGFjZ2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjA0MzAsImV4cCI6MjA3MTkzNjQzMH0.PcnI08CuGqph55ZfQtNaSbtY4JnSobiOGwn9v0J3K88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});